Initial iteration of the BPE Tokenizer.
Refactored pretokenization logic into a dedicated class to be shared across trainer and tokenizer.

Half of the test cases are passing, as well as a newly added test case based on assignment 1's instruction. Need to investigate other failing tests.

=================================================================================== test session starts ====================================================================================
platform darwin -- Python 3.12.11, pytest-8.4.1, pluggy-1.6.0
rootdir: /Users/chenwang/Desktop/github/cs336/assignment1-basics
configfile: pyproject.toml
plugins: line-profiler-0.2.1, jaxtyping-0.3.2, profiling-1.8.1
collected 26 items

tests/test_tokenizer.py::test_roundtrip_empty PASSED
tests/test_tokenizer.py::test_empty_matches_tiktoken PASSED
tests/test_tokenizer.py::test_roundtrip_single_character PASSED
tests/test_tokenizer.py::test_single_character_matches_tiktoken PASSED
tests/test_tokenizer.py::test_roundtrip_single_unicode_character PASSED
tests/test_tokenizer.py::test_single_unicode_character_matches_tiktoken PASSED
tests/test_tokenizer.py::test_roundtrip_ascii_string PASSED
tests/test_tokenizer.py::test_small PASSED
tests/test_tokenizer.py::test_ascii_string_matches_tiktoken FAILED
tests/test_tokenizer.py::test_roundtrip_unicode_string PASSED
tests/test_tokenizer.py::test_unicode_string_matches_tiktoken FAILED
tests/test_tokenizer.py::test_roundtrip_unicode_string_with_special_tokens FAILED
tests/test_tokenizer.py::test_unicode_string_with_special_tokens_matches_tiktoken FAILED
tests/test_tokenizer.py::test_overlapping_special_tokens FAILED
tests/test_tokenizer.py::test_address_roundtrip PASSED
tests/test_tokenizer.py::test_address_matches_tiktoken FAILED
tests/test_tokenizer.py::test_german_roundtrip PASSED
tests/test_tokenizer.py::test_german_matches_tiktoken FAILED
tests/test_tokenizer.py::test_tinystories_sample_roundtrip PASSED
tests/test_tokenizer.py::test_tinystories_matches_tiktoken FAILED
tests/test_tokenizer.py::test_encode_special_token_trailing_newlines FAILED
tests/test_tokenizer.py::test_encode_special_token_double_newline_non_whitespace FAILED
tests/test_tokenizer.py::test_encode_iterable_tinystories_sample_roundtrip FAILED
tests/test_tokenizer.py::test_encode_iterable_tinystories_matches_tiktoken FAILED
tests/test_tokenizer.py::test_encode_iterable_memory_usage SKIPPED (rlimit support for non-linux systems is spotty.)
tests/test_tokenizer.py::test_encode_memory_usage SKIPPED (rlimit support for non-linux systems is spotty.)

========================================================================================= FAILURES =========================================================================================
____________________________________________________________________________ test_ascii_string_matches_tiktoken ____________________________________________________________________________

    def test_ascii_string_matches_tiktoken():
        reference_tokenizer = tiktoken.get_encoding("gpt2")
        tokenizer = get_tokenizer_from_vocab_merges_path(
            vocab_path=VOCAB_PATH, merges_path=MERGES_PATH, special_tokens=["<|endoftext|>"]
        )
        test_string = "Hello, how are you?"

        reference_ids = reference_tokenizer.encode(test_string)
        ids = tokenizer.encode(test_string)
        # assert ids == reference_ids

        tokenized_string = [tokenizer.decode([x]) for x in ids]
>       assert tokenized_string == ["Hello", ",", " how", " are", " you", "?"]
E       AssertionError: assert ['He', 'llo',...', ' ar', ...] == ['Hello', ','..., ' you', '?']
E
E         At index 0 diff: 'He' != 'Hello'
E         Left contains 4 more items, first extra item: 'e'
E
E         Full diff:
E           [
E         +     'He',...
E
E         ...Full output truncated (18 lines hidden), use '-vv' to show

tests/test_tokenizer.py:223: AssertionError
___________________________________________________________________________ test_unicode_string_matches_tiktoken ___________________________________________________________________________

    def test_unicode_string_matches_tiktoken():
        reference_tokenizer = tiktoken.get_encoding("gpt2")
        tokenizer = get_tokenizer_from_vocab_merges_path(
            vocab_path=VOCAB_PATH, merges_path=MERGES_PATH, special_tokens=["<|endoftext|>"]
        )
        test_string = "Héllò hôw are ü? 🙃"

        reference_ids = reference_tokenizer.encode(test_string)
        ids = tokenizer.encode(test_string)
>       assert ids == reference_ids
E       AssertionError: assert [39, 2634, 29...110, 289, ...] == [39, 2634, 29...110, 289, ...]
E
E         At index 8 diff: 610 != 389
E         Left contains 2 more items, first extra item: 247
E
E         Full diff:
E           [
E               39,...
E
E         ...Full output truncated (22 lines hidden), use '-vv' to show

tests/test_tokenizer.py:249: AssertionError
____________________________________________________________________ test_roundtrip_unicode_string_with_special_tokens _____________________________________________________________________

    def test_roundtrip_unicode_string_with_special_tokens():
        tokenizer = get_tokenizer_from_vocab_merges_path(
            vocab_path=VOCAB_PATH, merges_path=MERGES_PATH, special_tokens=["<|endoftext|>"]
        )
        test_string = "Héllò hôw <|endoftext|><|endoftext|> are ü? 🙃<|endoftext|>"
        encoded_ids = tokenizer.encode(test_string)
        tokenized_string = [tokenizer.decode([x]) for x in encoded_ids]
        # Ensure the special <|endoftext|> token is preserved
>       assert tokenized_string.count("<|endoftext|>") == 3
E       AssertionError: assert 0 == 3
E        +  where 0 = <built-in method count of list object at 0x107ac7640>('<|endoftext|>')
E        +    where <built-in method count of list object at 0x107ac7640> = ['H', 'é', 'll', '�', '�', ' h', ...].count

tests/test_tokenizer.py:263: AssertionError
_________________________________________________________________ test_unicode_string_with_special_tokens_matches_tiktoken _________________________________________________________________

    def test_unicode_string_with_special_tokens_matches_tiktoken():
        reference_tokenizer = tiktoken.get_encoding("gpt2")
        tokenizer = get_tokenizer_from_vocab_merges_path(
            vocab_path=VOCAB_PATH, merges_path=MERGES_PATH, special_tokens=["<|endoftext|>"]
        )
        test_string = "Héllò hôw <|endoftext|><|endoftext|> are ü? 🙃<|endoftext|>"

        reference_ids = reference_tokenizer.encode(test_string, allowed_special={"<|endoftext|>"})
        ids = tokenizer.encode(test_string)
>       assert ids == reference_ids
E       AssertionError: assert [39, 2634, 29...110, 289, ...] == [39, 2634, 29...110, 289, ...]
E
E         At index 8 diff: 1279 != 220
E         Left contains 21 more items, first extra item: 1069
E
E         Full diff:
E           [
E               39,...
E
E         ...Full output truncated (49 lines hidden), use '-vv' to show

tests/test_tokenizer.py:278: AssertionError
_____________________________________________________________________________ test_overlapping_special_tokens ______________________________________________________________________________

    def test_overlapping_special_tokens():
        tokenizer = get_tokenizer_from_vocab_merges_path(
            vocab_path=VOCAB_PATH,
            merges_path=MERGES_PATH,
            special_tokens=["<|endoftext|>", "<|endoftext|><|endoftext|>"],
        )
        test_string = "Hello, how <|endoftext|><|endoftext|> are you?<|endoftext|>"

        ids = tokenizer.encode(test_string)
        tokenized_string = [tokenizer.decode([x]) for x in ids]
        # Ensure the double <|endoftext|><|endoftext|> is preserved as a single token
>       assert tokenized_string.count("<|endoftext|>") == 1
E       AssertionError: assert 0 == 1
E        +  where 0 = <built-in method count of list object at 0x1079f13c0>('<|endoftext|>')
E        +    where <built-in method count of list object at 0x1079f13c0> = ['He', 'llo', ',', ' ho', 'w', ' <', ...].count

tests/test_tokenizer.py:295: AssertionError
______________________________________________________________________________ test_address_matches_tiktoken _______________________________________________________________________________

    def test_address_matches_tiktoken():
        reference_tokenizer = tiktoken.get_encoding("gpt2")
        tokenizer = get_tokenizer_from_vocab_merges_path(
            vocab_path=VOCAB_PATH,
            merges_path=MERGES_PATH,
        )
        corpus_path = FIXTURES_PATH / "address.txt"
        with open(corpus_path) as f:
            corpus_contents = f.read()
        reference_ids = reference_tokenizer.encode(corpus_contents)
        ids = tokenizer.encode(corpus_contents)
>       assert ids == reference_ids
E       AssertionError: assert [37, 454, 629... 68, 290, ...] == [15137, 4776,...12, 2084, ...]
E
E         At index 0 diff: 37 != 15137
E         Left contains 344 more items, first extra item: 6837
E
E         Full diff:
E           [
E         -     15137,...
E
E         ...Full output truncated (1159 lines hidden), use '-vv' to show

tests/test_tokenizer.py:324: AssertionError
_______________________________________________________________________________ test_german_matches_tiktoken _______________________________________________________________________________

    def test_german_matches_tiktoken():
        reference_tokenizer = tiktoken.get_encoding("gpt2")
        tokenizer = get_tokenizer_from_vocab_merges_path(
            vocab_path=VOCAB_PATH,
            merges_path=MERGES_PATH,
        )
        corpus_path = FIXTURES_PATH / "german.txt"
        with open(corpus_path) as f:
            corpus_contents = f.read()
        reference_ids = reference_tokenizer.encode(corpus_contents)
        ids = tokenizer.encode(corpus_contents)
>       assert ids == reference_ids
E       AssertionError: assert [18683, 68, 1...8, 44919, ...] == [32423, 406, ...00, 2059, ...]
E
E         At index 0 diff: 18683 != 32423
E         Left contains 91 more items, first extra item: 44919
E
E         Full diff:
E           [
E         -     32423,...
E
E         ...Full output truncated (493 lines hidden), use '-vv' to show

tests/test_tokenizer.py:353: AssertionError
____________________________________________________________________________ test_tinystories_matches_tiktoken _____________________________________________________________________________

    def test_tinystories_matches_tiktoken():
        reference_tokenizer = tiktoken.get_encoding("gpt2")
        tokenizer = get_tokenizer_from_vocab_merges_path(
            vocab_path=VOCAB_PATH, merges_path=MERGES_PATH, special_tokens=["<|endoftext|>"]
        )
        corpus_path = FIXTURES_PATH / "tinystories_sample.txt"
        with open(corpus_path) as f:
            corpus_contents = f.read()
        reference_ids = reference_tokenizer.encode(corpus_contents, allowed_special={"<|endoftext|>"})
        ids = tokenizer.encode(corpus_contents)
>       assert ids == reference_ids
E       AssertionError: assert [198, 2202, 3...261, 257, ...] == [198, 7454, 2...640, 612, ...]
E
E         At index 1 diff: 2202 != 7454
E         Left contains 839 more items, first extra item: 46668
E
E         Full diff:
E           [
E               198,...
E
E         ...Full output truncated (3189 lines hidden), use '-vv' to show

tests/test_tokenizer.py:381: AssertionError
_______________________________________________________________________ test_encode_special_token_trailing_newlines ________________________________________________________________________

    def test_encode_special_token_trailing_newlines():
        reference_tokenizer = tiktoken.get_encoding("gpt2")
        tokenizer = get_tokenizer_from_vocab_merges_path(
            vocab_path=VOCAB_PATH, merges_path=MERGES_PATH, special_tokens=["<|endoftext|>"]
        )
        corpus_path = FIXTURES_PATH / "special_token_trailing_newlines.txt"
        with open(corpus_path) as f:
            corpus_contents = f.read()
        reference_ids = reference_tokenizer.encode(corpus_contents, allowed_special={"<|endoftext|>"})
        ids = tokenizer.encode(corpus_contents)
>       assert ids == reference_ids
E       AssertionError: assert [27, 91, 3111...1069, 83, ...] == [50256, 628]
E
E         At index 0 diff: 27 != 50256
E         Left contains 7 more items, first extra item: 31110
E
E         Full diff:
E           [
E         -     50256,...
E
E         ...Full output truncated (10 lines hidden), use '-vv' to show

tests/test_tokenizer.py:397: AssertionError
_________________________________________________________________ test_encode_special_token_double_newline_non_whitespace __________________________________________________________________

    def test_encode_special_token_double_newline_non_whitespace():
        reference_tokenizer = tiktoken.get_encoding("gpt2")
        tokenizer = get_tokenizer_from_vocab_merges_path(
            vocab_path=VOCAB_PATH, merges_path=MERGES_PATH, special_tokens=["<|endoftext|>"]
        )
        corpus_path = FIXTURES_PATH / "special_token_double_newlines_non_whitespace.txt"
        with open(corpus_path) as f:
            corpus_contents = f.read()
        reference_ids = reference_tokenizer.encode(corpus_contents, allowed_special={"<|endoftext|>"})
        ids = tokenizer.encode(corpus_contents)
>       assert ids == reference_ids
E       AssertionError: assert [27, 91, 3111...1069, 83, ...] == [50256, 198, 198, 33407, 0]
E
E         At index 0 diff: 27 != 50256
E         Left contains 9 more items, first extra item: 83
E
E         Full diff:
E           [
E         -     50256,...
E
E         ...Full output truncated (18 lines hidden), use '-vv' to show

tests/test_tokenizer.py:413: AssertionError
____________________________________________________________________ test_encode_iterable_tinystories_sample_roundtrip _____________________________________________________________________

    def test_encode_iterable_tinystories_sample_roundtrip():
        tokenizer = get_tokenizer_from_vocab_merges_path(
            vocab_path=VOCAB_PATH,
            merges_path=MERGES_PATH,
        )
        all_ids = []
        with open(FIXTURES_PATH / "tinystories_sample.txt") as f:
>           for _id in tokenizer.encode_iterable(f):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E           TypeError: 'NoneType' object is not iterable

tests/test_tokenizer.py:426: TypeError
____________________________________________________________________ test_encode_iterable_tinystories_matches_tiktoken _____________________________________________________________________

    def test_encode_iterable_tinystories_matches_tiktoken():
        reference_tokenizer = tiktoken.get_encoding("gpt2")
        tokenizer = get_tokenizer_from_vocab_merges_path(
            vocab_path=VOCAB_PATH, merges_path=MERGES_PATH, special_tokens=["<|endoftext|>"]
        )
        corpus_path = FIXTURES_PATH / "tinystories_sample.txt"
        with open(corpus_path) as f:
            corpus_contents = f.read()
        reference_ids = reference_tokenizer.encode(corpus_contents, allowed_special={"<|endoftext|>"})
        all_ids = []
        with open(FIXTURES_PATH / "tinystories_sample.txt") as f:
>           for _id in tokenizer.encode_iterable(f):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E           TypeError: 'NoneType' object is not iterable

tests/test_tokenizer.py:444: TypeError
===================================================================================== warnings summary =====================================================================================
.venv/lib/python3.12/site-packages/torch/nn/modules/transformer.py:20
  /Users/chenwang/Desktop/github/cs336/assignment1-basics/.venv/lib/python3.12/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================================================================================= short test summary info ==================================================================================
FAILED tests/test_tokenizer.py::test_ascii_string_matches_tiktoken - AssertionError: assert ['He', 'llo',...', ' ar', ...] == ['Hello', ','..., ' you', '?']
FAILED tests/test_tokenizer.py::test_unicode_string_matches_tiktoken - AssertionError: assert [39, 2634, 29...110, 289, ...] == [39, 2634, 29...110, 289, ...]
FAILED tests/test_tokenizer.py::test_roundtrip_unicode_string_with_special_tokens - AssertionError: assert 0 == 3
FAILED tests/test_tokenizer.py::test_unicode_string_with_special_tokens_matches_tiktoken - AssertionError: assert [39, 2634, 29...110, 289, ...] == [39, 2634, 29...110, 289, ...]
FAILED tests/test_tokenizer.py::test_overlapping_special_tokens - AssertionError: assert 0 == 1
FAILED tests/test_tokenizer.py::test_address_matches_tiktoken - AssertionError: assert [37, 454, 629... 68, 290, ...] == [15137, 4776,...12, 2084, ...]
FAILED tests/test_tokenizer.py::test_german_matches_tiktoken - AssertionError: assert [18683, 68, 1...8, 44919, ...] == [32423, 406, ...00, 2059, ...]
FAILED tests/test_tokenizer.py::test_tinystories_matches_tiktoken - AssertionError: assert [198, 2202, 3...261, 257, ...] == [198, 7454, 2...640, 612, ...]
FAILED tests/test_tokenizer.py::test_encode_special_token_trailing_newlines - AssertionError: assert [27, 91, 3111...1069, 83, ...] == [50256, 628]
FAILED tests/test_tokenizer.py::test_encode_special_token_double_newline_non_whitespace - AssertionError: assert [27, 91, 3111...1069, 83, ...] == [50256, 198, 198, 33407, 0]
FAILED tests/test_tokenizer.py::test_encode_iterable_tinystories_sample_roundtrip - TypeError: 'NoneType' object is not iterable
FAILED tests/test_tokenizer.py::test_encode_iterable_tinystories_matches_tiktoken - TypeError: 'NoneType' object is not iterable
=================================================================== 12 failed, 12 passed, 2 skipped, 1 warning in 4.09s ====================================================================